# Generated by Django 6.0.7 on 2026-09-08 07:40

import accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_blacklistpolicy_bot_path_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=accounts.models.download_file_upload_to)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='kind',
            field=models.CharField(choices=[('manual', 'manual'), ('rate', 'rate'), ('login', 'login'), ('limit', 'limit'), ('mybox', 'mybox'), ('bot', 'bot'), ('unknown', 'unknown')], max_length=16),
        ),
    ]
