# Generated by Django 6.0.7 on 2026-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_downloadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfile',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
