# Generated by Django 6.0.7 on 2026-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_downloadfile_token_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfile',
            name='token',
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='filename',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
