# Generated by Django 6.0.7 on 2026-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_downloadfile_by_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistpolicy',
            name='download_redirect_url',
            field=models.URLField(default='https://www.naver.com/', max_length=500),
        ),
    ]
